### ISSUE TITLE
Support for previous versions of PHP

### ISSUE THREAD

**Issue by lisachenko** [Ocramius/PackageVersions#10]
Hello, I liked this library very much and want to use it for my projects. From what I can see, there is no strict need in PHP7, it can easily be used with PHP5.5 and PHP5.6 as well. I know your position about moving forward to the new versions, but sometimes this can be a painful to upgrade to PHP7 due to special extensions that aren't ported yet.

So, would you mind make it PHP>=5.5 compatible? Don't want to create a fork only for removing STH and RTH (

**Comment by Ocramius** [comment]
I don't really want to support 5.x on any new packages that I'm developing for fun and for my own needs. I get why you want this to happen (support 5.*), but we should all really just join effort and push for 7.* requirements everywhere.

What package would need it, and why can't it depend on 7.* for the new version that introduces this dependency?

**Comment by lisachenko** [comment]
Of course, all new stuff should just work with php7. This is our global goal and we should go to it. But there is internal projects that are used with old code, so I can release my component for PHP7, but it won't be used in old environment. 5.5 and 5.6 have a lot of working apps right now, sigh.

I think about previous versions of PHP from admin side as `--prefer-lowest` flag, so if code can run on all major versions, it will be nice.

Anyway, thanks for this library!

**Comment by Ocramius** [comment]
Since it's for an internal project, I suggest forking and then (immediately) deprecating your own version, using it until an upgrade to PHP7 is viable.

While I understand the problem that you are exposing, if I start downgrading the requirements people will not aim at the upgrade anymore, while that is my explicit intent.
