### ISSUE TITLE
Cannot locate `composer.lock` nor `installed.json` when using package with `--no-scripts`

### ISSUE THREAD

**Issue by PhilETaylor** [Ocramius/PackageVersions#101]
```
Fatal error: Uncaught UnexpectedValueException: PackageVersions could not locate the `vendor/composer/installed.json` or your `composer.lock` location. This is assumed to be in ["\/var\/www\/current\/public\/vendor\/composer\/installed.json","\/var\/www\/current\/public\/composer.lock","\/var\/www\/current\/vendor\/ocramius\/package-versions\/src\/PackageVersions\/..\/..\/composer.lock"]. 

If you customized your composer vendor directory and ran composer installation with --no-scripts or if you deployed without the required composer files, then you are on your own, and we can't really help you. Fix your shit and cut the tooling some slack. 

in /var/www/current/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php:93 Stack trace: #0 /var/www/current/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php(43): PackageVersions\FallbackVersions::getPackageData() #1 /var/www/current/vendor/ocramius/package-versions/src/PackageVersions/Versions.php(28): PackageVersions\FallbackVersions::getVe in /var/www/current/vendor/ocramius/package-versions/src/PackageVersions/FallbackVersions.php on line 93
```

Not acceptable to Fatal Error on a production site on a point upgrade ... way to go... 

Lucky I silence errors, else your offensive language would be shown to my paying visitors too :( 

**My composer.json and composer.lock are in the default places**, in the root of the project where they have always been.

**My vendor director is in the default place**, in the root of the project where composer put it.

Yes I run `APP_ENV=prod composer install --profile --prefer-dist --no-scripts --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader` with `no-scripts` when building my production docker images

It is not uncommon to build docker images with this kind of composer install no-scripts command.

related to https://github.com/Ocramius/PackageVersions/issues/18

I never even knew I used `ocramius/package-versions` - but a composer why gives

```
doctrine/migrations             v2.1.0  requires  ocramius/package-versions (^1.3)
jean85/pretty-package-versions  1.2     requires  ocramius/package-versions (^1.2.0)
ocramius/proxy-manager          2.2.2   requires  ocramius/package-versions (^1.1.3)
```

Time to peg you at 1.4.x :-(

**Comment by Ocramius** [comment]
Hey there,

Besides that, the CI builds test `--no-scripts`, so I'd need a reproducer to get this reproduced and understand why it crashes for you.

**Comment by profuel** [comment]
I feel that you had to make 2.0 release, since dropping PHP 7.2.0 s a major.

**Comment by Ocramius** [comment]
Yep, seems like the `--no-scripts` CI entry is not testing what it's supposed to test

**Comment by Ocramius** [comment]
@profuel bumping dependency versions is not a BC break, also not according to SemVer.

See also https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html (to not repeat myself there).

**Comment by Ocramius** [comment]
Turns out that `getcwd()` may return an empty path in https://github.com/Ocramius/PackageVersions/blob/da0d9d34cd5df6b35756a00827aaeca7d903868d/src/PackageVersions/FallbackVersions.php#L63-L65

Rolling out a fix and release for it.

**Comment by Ocramius** [comment]
Released as `1.5.1`

**Comment by PhilETaylor** [comment]
Thanks for addressing this so quickly. 

I can confirm, in my situation, v1.5.1 fixes the fatal error in production.

**Comment by PhilETaylor** [comment]
And lastly, my docker instances are built on Alpine images... not sure if `getcwd()` does crazy things in Alpine, but thought I would mention the OS just in case that helps.
