### ISSUE TITLE
Version 1.2.0 and PHP 7.0

### ISSUE THREAD

**Issue by salcode** [Ocramius/PackageVersions#103]
Thanks for sharing this great package. I think the required PHP version in release [1.2.0](https://github.com/Ocramius/PackageVersions/releases/tag/1.2.0) may be incorrect.

In the `1.2.0` version of [composer.json](https://github.com/Ocramius/PackageVersions/blob/1.2.0/composer.json) the required PHP version is `~7.0`

```
"require": {
        "php":                 "~7.0",
        "composer-plugin-api": "^1.0"
    },
```

however the resulting code generated includes

```
public const ROOT_PACKAGE_NAME
```

and *Class constant visibility modifiers* was only introduced in [PHP 7.1.0](https://www.php.net/releases/7_1_0.php)

Would you be open to the idea of a `1.2.1` release that changes the required PHP version in `composer.json` from `~7.0` to `~7.1`?

Thanks for your consideration.

**Comment by Ocramius** [comment]
Good point! Lemme go ahead and do that right away :+1:

**Comment by Ocramius** [comment]
I just checked: 1.2.0 does generate `PackageVersions\Versions::VERSIONS`, but not `PackageVersions\Versions::ROOT_PACKAGE_NAME`:

https://github.com/Ocramius/PackageVersions/blob/ad8a245decad4897cc6b432743913dad0d69753c/src/PackageVersions/Installer.php#L32

`ROOT_PACKAGE_VERSION` was introduced in 1.3.0:

https://github.com/Ocramius/PackageVersions/blob/1.3.0/src/PackageVersions/Installer.php#L32

1.3.0 requires PHP 7.1:

https://github.com/Ocramius/PackageVersions/blob/1.3.0/composer.json#L13

**Comment by Ocramius** [comment]
Na, just pin to `^1.2` and you are fine.

Please stop the proliferation of backports: they don't aid the ecosystem in moving forward.

**Comment by clxmstaab** [comment]
> Please stop the proliferation of backports: they don't aid the ecosystem in moving forward.

please accept that the majority of people out there cannot update their php-version as you want them to.
we need the features of 1.3+ and since you push the min-php version so hard this does not work

**Comment by Ocramius** [comment]
Want new features? Upgrade!

It's that simple.

Having a lot of backports only fragments thr ecosystem and allows people to be lazy about their upgrade policy.

There only legit reason to not have environments upgraded to 7.2 or 7.3 in 2019 is some ancient bug that cannot be easily fixed, and only works on older environments. Everything else is laziness, especially if you say "we need the new features".

**Comment by clxmstaab** [comment]
thats your point of view.

on the other end there are LTS releases and companies who need to pay for servers and their migration when updating php

**Comment by Ocramius** [comment]
LTS releases are in **feature freeze**: they don't get the newest and greatest stuff, and that's OK.

**Comment by clxmstaab** [comment]
yes the php version is in feature freeze... doesnt mean all my libs and everything arround it is in feature freeze though

**Comment by Ocramius** [comment]
That's what LTS means: you develop new stuff with **current stable**, you deploy old stuff with **old stable**.

See for example #86 

Meanwhile, closing and locking here: not open for further discussion on the topic.
