### ISSUE TITLE
changelog not updated

### ISSUE THREAD

**Issue by tarlepp** [Ocramius/PackageVersions#104]
It seems that eg PHP 7.2 support has been dropped, but changelog doesn't tell this at all. I'm assuming that changelog hasn't updated a quite long time, so why is that?

**Comment by Ocramius** [comment]
True, haven't put it in changelog, but `comppser.json` is correctly filtering out `<7.2.0`.

Will add a line to the release notes.

**Comment by Ocramius** [comment]
Btw, if you need release notes to be mirrored in `CHANGELOG.md`, please send a patch 👍
