### ISSUE TITLE
Handle missing source reference gracefully

### ISSUE THREAD

**Issue by simonihmig** [Ocramius/PackageVersions#119]
When there is no `.git` data available (e.g. docker setup with only a subfolder of the repo as the shared volume), the version of the root package is returned as something like `1.0.0@` 
https://github.com/Ocramius/PackageVersions/blob/5be0adfef1e5c5708b8584ff348d3e0a29ff1c2a/src/PackageVersions/Installer.php#L207

I wonder if this shouldn't be handled more gracefully, to detect the empty `$rootPackage->getSourceReference()` and return `1.0.0` instead!?

**Comment by Ocramius** [comment]
the `@` is intentional, and downstream packages depend on it. If you need the version to be "pretty", I suggest using https://github.com/Jean85/pretty-package-versions instead :+1:

**Comment by simonihmig** [comment]
Got it, thanks for the quick feedback! 🙏
