### ISSUE TITLE
Packages don't always have a source/reference

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/PackageVersions#12]
Moved from https://github.com/Ocramius/ProxyManager/issues/294

Basically, when using something like following:

```json
{
    "require": {
        "jquery/jquery":  "1.10.*"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "jquery/jquery",
                "version": "1.10.2",
                "dist": {
                    "url": "http://code.jquery.com/jquery-1.10.2.js",
                    "type": "file"
                }
            }
        }
    ]
}
```

As you can see, this package has no `source` reference, as it comes from a repository (in-lined in the `composer.json`) that has no such information. Therefore, [this call](https://github.com/Ocramius/PackageVersions/blob/56253310fb94b3086fa123f5f3e7ab76723594aa/src/PackageVersions/Installer.php#L189) fails, causing a general failure of the code generation in the script.

**Comment by magnetik** [comment]
yay ! Do you mind tagging a new version?

**Comment by Ocramius** [comment]
@magnetik yarp, gonna happen now.

**Comment by Ocramius** [comment]
@magnetik released

**Comment by magnetik** [comment]
Awesome :)
