### ISSUE TITLE
Version 1.6.0 breaks dependencies

### ISSUE THREAD

**Issue by tems99** [Ocramius/PackageVersions#123]
The 1.6.0 release sets the minimum version to PHP to 7.4.

This causes errors in composer install for libraries that depend on this that use ^ in composer.
One of the packages in doctrine/common includes this library.

Maybe bump to v2?

**Comment by Ocramius** [comment]
Duplicate of #105

**Comment by Ocramius** [comment]
Please also read carefully: https://github.com/Ocramius/PackageVersions/issues/105#issuecomment-516617164
