### ISSUE TITLE
v1.7.0 PHP Parse error Installer.php on line 34

### ISSUE THREAD

**Issue by abarke** [Ocramius/PackageVersions#126]
$ composer update

Installing ocramius/package-versions (1.7.0): Cloning 651c372efc from cache

PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in ...\vendor\ocramius\package-versions\src\PackageVersions\Installer.php on line 34

**Comment by Ocramius** [comment]
Duplicate of #105: please read the full thread
