### ISSUE TITLE
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by i-kitchen** [Ocramius/PackageVersions#131]
Hello!

Was running a pipeline and it keeps failing at the step where I run:
`composer install --no-interaction --no-dev --optimize-autoloader --no-progress --no-suggest --ignore-platform-reqs`

The full error:
```
Installing ocramius/package-versions (1.7.0): Downloading (100%)
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /builds/enterprise-systems/web-phone/symfony/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34
Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /builds/enterprise-systems/web-phone/symfony/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34
```

Is this a bug that was pushed out with this release or am I using a flag that is incompatible with the current release?

Thanks for your time!

**Comment by i-kitchen** [comment]
Nevermind I see from previously closed issues what the problem is.

**Comment by Ocramius** [comment]
Duplicate of #105
