### ISSUE TITLE
Conflicts Composer 2.x in PHP 7.3

### ISSUE THREAD

**Issue by zonuexe** [Ocramius/PackageVersions#145]
Conflicts occur when installing packages that depend on `ocramius/package-versions` with PHP 7.3 or below and Composer2. (ex: https://github.com/phpactor/phpactor/issues/1080)

The last `ocramius/package-versions` version for PHP 7.3 is **1.5.1**, but this version does not support `composer-plugin-api:2.0.0`.

Can you apply https://github.com/Ocramius/PackageVersions/pull/133 to 1.5.1?

**Comment by Ocramius** [comment]
Heya, #133 is out of question. Upgrading to PHP 7.4 is the lowest resistance path, and also the reason why I keep dependencies this strict :-)

For now, working on #143 to move this package to `composer/composer:^2` and `php:^7.4.7`

**Comment by zonuexe** [comment]
That's right, I and you share the idea that the latest PHP and Composer are the best solutions.
However, PHP7.3 is still used in the real world, and the life for security support is one and a half years left.
Your package is trusted by QA tools like Psalm and Phpactor, and I believe it is worth removing the conflict with 7.3.

I will not make any further claims to you on this matter. Thank you for your reply!

**Comment by Ocramius** [comment]
Those packages can use any of the `1.x` releases - composer 2.0 is still in alpha.
