### ISSUE TITLE
Fatal error Undefined class constant 'VERSIONS'

### ISSUE THREAD

**Issue by alexander-schranz** [Ocramius/PackageVersions#147]
> !!  Fatal error: Uncaught Error: Undefined class constant 'VERSIONS' in /tmp/Sulu/sulu-develop.localhost/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/Util/IdentifierSuffixer.php:50

There seems to be accidentally a bc break introduced in https://github.com/Ocramius/PackageVersions/pull/146/files/df8ee422f3f361420e35db8ba57a1d5799c995b0#diff-1240b8c874ee2d72c077a8c3401fede3. Where the VERSIONS constant not longer exist which is access by the [proxy-manager](https://github.com/Ocramius/ProxyManager/blob/2.8.0/src/ProxyManager/Generator/Util/IdentifierSuffixer.php#L50) in the newest version.

~~For this running into this issue add  conflict the `1.10.0` in your composer.json:~~ **EDIT** Update proxy-manager to the soon released 2.8.1 :)

**Comment by Ocramius** [comment]
Not a BC break: if the error occurs in `ocramius/proxy-manager`, it is relying on an `@internal` detail, and that must be fixed downstream.

**Comment by alexander-schranz** [comment]
closed in favor of https://github.com/Ocramius/ProxyManager/issues/617
