### ISSUE TITLE
Support for Versions::ROOT_PACKAGE_NAME is broken

### ISSUE THREAD

**Issue by stof** [Ocramius/PackageVersions#148]
`Versions::getVersion(Versions::ROOT_PACKAGE_NAME)` is expected to return the version of the root package.
But currently, the implementation forwards such call to `Composer\InstalledVersions::getVersion()` directly, which does not support the root package as package name. Info about the root package is exposed through `Composer\InstalledVersions::getRootPackage()`

**Comment by Ocramius** [comment]
I think `Versions::ROOT_PACKAGE_NAME` should be overall deprecated (https://github.com/Ocramius/PackageVersions/issues/142, https://github.com/Ocramius/PackageVersions/issues/139)

**Comment by stof** [comment]
sure. But in the meantime, it should still work. for now, there is no way to get the info about the root package anymore in this library.

**Comment by Ocramius** [comment]
Hmm, wait, so `Composer\InstalledVersions::getVersion()` has no root package info **at all**?

**Comment by stof** [comment]
`Composer\InstalledVersions::getVersion()` is only about packages installed in vendors (same than `Composer\InstalledVersions::isInstalled()`.
The info about the root package are available through a separate `Composer\InstalledVersions::getRootPackage()` method.

**Comment by Ocramius** [comment]
I see, makes sense. Will indeed need some trickery to work :-\

**Comment by stof** [comment]
Well, I think this could look like this:

```php
function getVersion(string $packageName)
{
    if ($packageName === self::ROOT_PACKAGE_NAME) {
        return \Composer\InstalledVersions::getRootPackage()['version']; // Or whatever is needed to output the right info
    }

    // existing code stays here
}
```

**Comment by Ocramius** [comment]
This seems to be only affecting the "fallback" version, when `'unknown/root-package@UNKNOWN'` is used for a lookup. Not a massive fix though :-)
