### ISSUE TITLE
Packages need not have a reference

### ISSUE THREAD

**Issue by GrahamCampbell** [Ocramius/PackageVersions#157]
```php
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "foo/bar",
                "version": "1.0.0",
                "dist": {
                    "url": "https://example.com/1.0.0.zip",
                    "type": "zip"
                }
            }
        }
    ]
    "require": {
        "foo/bar": "^1.0"
    }
}
```

```php
Versions::getVersion('foo/bar');
```

Using version 2.0.0 of this package. The code in `getVersion` tries to concat `null` to a string, and leaves a trailing at sign.

Expected behaviour: for null to be tested, and the `@` to be omitted too.

**Comment by Ocramius** [comment]
The missing ref used to be an empty string also before, afaik (expected). Usually happens when no `git` information is available, for example in a root package.

**Comment by Ocramius** [comment]
Closing here: this is expected behavior that didn't change in a loooooooong time.
