### ISSUE TITLE
I can't update composer anymore

### ISSUE THREAD

**Issue by ItIsInspiring** [Ocramius/PackageVersions#159]
Hi Ocramis, 
i am a junior developer. I am not sure to use properly the conventions "how to create an issue" but since this morning, i can't use composer anymore from my laravel6/homestead project.

I have this message in my terminal 

`PHP Fatal error:  Constant expression contains invalid operations in /Users/USER/www/PROJECT/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34`

it seems to be a problem related to the use of heredoc syntax.

I can't do nothing but erase it, without really knowing the consequences.

Would you give some advices to a fresh new developper, please ?

thanks

**Comment by Ocramius** [comment]
Hey @ItIsInspiring!

I think what happened is that you ran a `composer update` from an environment running a newer PHP version.

Here's what you could do:

 1. `rm -rf vendor` (this is generally OK, unless you have sensitive stuff in there, but you really shouldn't!)
 2. `composer update ocramius/package-versions` from **within** your VM

That should align the version of `ocramius/package-versions` to what's compatible with your VM :-)

**Comment by Ocramius** [comment]
Closing here due to no feedback.

**Comment by ItIsInspiring** [comment]
Oh sorry,
Thank you for you advices. It did not work the frist time i tried, but somehow, it is working now...
Thanks for your help.

**Comment by Ocramius** [comment]
@ItIsInspiring no worries, glad it worked out in the end :-)
