### ISSUE TITLE
Error at version 1.9 when I run composer update

### ISSUE THREAD

**Issue by Phalconline** [Ocramius/PackageVersions#163]
Composer version 1.10.8 2020-06-24 21:23:30

![image](https://user-images.githubusercontent.com/3986432/102385899-13583b00-3fd7-11eb-9cbd-6cd095234340.png)

**Comment by Ocramius** [comment]
You are most likely running `ocramius/package-versions` on a system with an older PHP version.

`1.9.0` requires PHP 7.4:

https://github.com/Ocramius/PackageVersions/blob/94c9d42a466c57f91390cdd49c81313264f49d85/composer.json#L13
