### ISSUE TITLE
Script to dump the output into different file formats

### ISSUE THREAD

**Issue by mablae** [Ocramius/PackageVersions#19]
~~A use case could be automated dumping into a DEPENDCIES.md
by CI. Dunno if it is out of scope of this lib, just an idea.~~

Deleted bullshit.

**Comment by Ocramius** [comment]
@mablae solved? I think you can just read the `PackageVersions::VERSIONS` constant?

**Comment by mablae** [comment]
Yeah, basically my issue was just written to fast without looking at the code correctly. 

Sorry for stealing your time.
