### ISSUE TITLE
Updating to composer 2.2.1 replaced ocaramius package-version to 1.11.99 which causes this : Fatal error: Class PackageVersions\Installer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall)

### ISSUE THREAD

**Issue by Rituparna007** [Ocramius/PackageVersions#194]
Hello

I have upgraded composer version to 2.2.1 and PHP version is 7.3.29. After upgrading I am getting this error 

 Installing ocramius/package-versions (1.5.1): Extracting archive
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.

Fatal error: Class PackageVersions\Installer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /var/www/book.grabrooms.com.dev.envoyer/releases/20211229142318/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 32
PHP Fatal error:  Class PackageVersions\Installer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /var/www/book.grabrooms.com.dev.envoyer/releases/20211229142318/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 32

Can you please guide me how can I solve this issue?

**Comment by Ocramius** [comment]
`composer/package-version-deprecated` is not this library: it is a fork that has gone completely sideways (and frankly wastes so much energy and time).

Please report issues at https://github.com/composer/package-versions-deprecated
