### ISSUE TITLE
Add convenience functionality to streamline format of returned versions

### ISSUE THREAD

**Issue by holtkamp** [Ocramius/PackageVersions#21]
Currently the returned versions 'might' be in different formats, for example:
- 'bower-asset/flag-icon-css' => '2.3.1@836eca11ecf437ae3d0f0c93dd245ab00d94cee1'
- 'bower-asset/font-awesome' => 'v4.6.3@8e241f209faa1dd2182c9fdc9c352d8806504a4e'

The part that I am interested in to generate an URL that points to these assets on a CDN is:
- 'bower-asset/flag-icon-css' => '2.3.1'
- 'bower-asset/font-awesome' => '4.6.3'

I find myself writing code like:

``` php
sprintf('//cdnjs.cloudflare.com/ajax/libs/font-awesome/%s/css/font-awesome.min.css', ltrim(current(explode('@', \PackageVersions\Versions::getVersion('bower-asset/font-awesome'))), 'v')),
```

maybe some convencience methods can be added to this library to:
- fetch only the version, excluding the hash of the commit
- strip the 'v' of the version

Maybe you consider this 'out-of-scope' for this library? Was just wondering 😄

**Comment by Ocramius** [comment]
@holtkamp you mean like https://github.com/Ocramius/PackageVersions/pull/9 ?

**Comment by holtkamp** [comment]
@Ocramius , mmm, yeah, guess that would cover it. Sorry, only looked at the issues, not the PR's...

**Comment by Ocramius** [comment]
Closing as per https://github.com/Ocramius/PackageVersions/issues/44 and https://github.com/Ocramius/PackageVersions/issues/43
