### ISSUE TITLE
Fatal error during travis build after update to 1.1.0

### ISSUE THREAD

**Issue by prolic** [Ocramius/PackageVersions#34]
```
Fatal error: Syntax only allowed in Hack files (<?hh) or with -v Eval.EnableHipHopSyntax=true in /home/travis/build/company/project/vendor/ocramius/package-versions/src/PackageVersions/Versions.php on line 147
```

**Comment by prolic** [comment]
Btw: PHP 7 only is used on travis.

**Comment by Ocramius** [comment]
Neither PackageVersions nor ProxyManager v2 officially support HHVM: can't
do much, since it's lagging back on language support

**Comment by prolic** [comment]
I am not using hhvm, but PHP 7 and travis builds are failing with 1.1.0 and passing with 1.0.4.

**Comment by prolic** [comment]
Unfortunately this is a private repository, but perhaps I can make a small test-repo to reproduce the issue for you, if necessary.

**Comment by Ocramius** [comment]
Does the problem present itself with master?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by prolic** [comment]
Yep, works with current master.

**Comment by Ocramius** [comment]
@prolic I'll tag a release then. Gimme a few minutes :-)

**Comment by prolic** [comment]
perfect, thanks.

**Comment by Ocramius** [comment]
https://github.com/Ocramius/PackageVersions/releases/tag/1.1.1
