### ISSUE TITLE
Custom exception

### ISSUE THREAD

**Issue by ThaDafinser** [Ocramius/PackageVersions#4]
Hello,

i have a use case, where i need to check if a package is installed.

I dunno yet if i like my current implementation...
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/PiwikDeviceDetector.php#L81-L83

If this would be a custom exception, this package could also be usefull to check if a package is installed at all https://github.com/Ocramius/PackageVersions/blob/a108adf44c4663bfb72858ea2fcd174acddd317e/src/PackageVersions/Installer.php#L41

**Comment by Ocramius** [comment]
That is a rather unusual way of approaching this problem. Regardless of that, though, we could provide raw access to the lock data in this package...

**Comment by ThaDafinser** [comment]
Yeah... sadly i needed to change it, since i could not get the unit tests run with `class_exists()` under PHP7/HHVM ...
https://github.com/ThaDafinser/UserAgentParser/blob/5c73356e06db8bffa0792b28938e3eec491fa7a1/src/Provider/PiwikDeviceDetector.php#L81-L83

**Comment by Ocramius** [comment]
@ThaDafinser is a change needed for now?

**Comment by ThaDafinser** [comment]
Not for now in my case. Need to get rid of php `5.6` support first...

**Comment by Ocramius** [comment]
@ThaDafinser when this becomes relevant, consider sending a PR for a custom exception + exception interface extending `Throwable`

**Comment by ThaDafinser** [comment]
@Ocramius my use cases to read metadata from the installed packages increased.

Based on your work (and https://github.com/mindplay-dk/composer-locator), i created those 2 WIP files, to get all informations i need.
https://gist.github.com/ThaDafinser/1dbb7c287717aa010c25f4e93d236ece

My question: Is there any intention to include all those information in your package? Otherwise i guess i would need to create a new plugin/package.

**Comment by Ocramius** [comment]
@ThaDafinser the question is: is it performance-sensitive? The aim of this package is to be performance-sensitive version information retrieval. If a `file_get_contents('composer.lock')` isn't a problem in your scenario, then it probably doesn't fit in this package.

**Comment by ThaDafinser** [comment]
Fast is always better...
Like provided in my example code, i nearly do the same like you did hear. But instead of just saving the version in the constant, i added all values of the package metdata
https://github.com/Ocramius/PackageVersions/blob/master/src/PackageVersions/Installer.php#L172-L174
https://gist.github.com/ThaDafinser/1dbb7c287717aa010c25f4e93d236ece#file-packagetemplate-php-L16
https://gist.github.com/ThaDafinser/1dbb7c287717aa010c25f4e93d236ece#file-installer-php-L59-L65

**Comment by Ocramius** [comment]
> Fast is always better...

Depends on effort and on what you are doing there. Specifically, if you are actually traversing a directory tree (seems like you want to work with directories there), you are already going to cause some I/O there, no?

**Comment by ThaDafinser** [comment]
I think we miss us both :smile: 

In my example code i also add all values (on composer install/update) to the constant like you do here already with the version only.
So you have all values ready in a class and no composer.json or composer.lock involved later.

Example result (after install/update):
```php
<?php
namespace PackageInfo;

use DateTime;
use DateTimeZone;
use PackageInfo\Exception\PackageNotInstalledException;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Package
{
    const PACKAGES = array (
  'foo/bar' => 
  array (
    'name' => 'foo/bar',
    'version' => '1.2.3',
    'time' => '2016-05-18 16:56:05'
    // all other composer.lock values...(description, type, license, keywords, ...)
  ),
  'baz/tab' => 
  array (
    'name' => 'baz/tab',
    'version' => '4.5.6',
    'time' => '2016-05-18 16:56:05'
    // all other composer.lock values...
  ),
  'tar/taz' => 
  array (
    'name' => 'tar/taz',
    'version' => '7.8.9',
    'time' => '2016-05-18 16:56:05'
    // all other composer.lock values...
  ),
);

    /**
     * 
     * @var string
     */
    private $name;
    
    /**
     * 
     * @param string $name
     * @throws PackageNotInstalledException
     */
    public function __construct($name)
    {
        $this->name = $name;
        
        if (! $this->isInstalled($name)) {
            throw new PackageNotInstalledException('Package "'.$name.'" is not installed');
        }
    }
    
    /**
     * Check if the given package is installed
     * 
     * @return boolean
     */
    public static function isInstalled($name)
    {
        if (array_key_exists($name, self::PACKAGES)) {
            return true;
        }
        
        return false;
    }
    
    /**
     * @return mixed
     */
    public function getValue($key)
    {
        $values = $this->getValues();
        
        if(array_key_exists($key, $values)){
            return $values[$key];
        }
        
        return null;
    }
    
    /**
     * @return array
     */
    public function getValues()
    {
        if(array_key_exists($this->getName(), self::PACKAGES)){
            return self::PACKAGES[$this->getName()];
        }
        
        return [];
    }
    
    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->getValue('description');
    }
    
    /**
     * @return string
     */
    public function getVersion()
    {
        return $this->getValue('version');
    }
    
    /**
     * @return string
     */
    public function getType()
    {
        return $this->getValue('type');
    }
    
    /**
     * @return array
     */
    public function getKeywords()
    {
        return $this->getValue('keywords');
    }
    
    /**
     * @return string
     */
    public function getHomepage()
    {
        return $this->getValue('homepage');
    }
    
    /**
     * Return the release date of the current installed version
     * 
     * @return DateTime
     */
    public function getVersionReleaseDate()
    {
        return new DateTime($this->getValue('time'), new DateTimeZone('UTC'));
    }
    
    /**
     * @return string|array
     */
    public function getLicense()
    {
        return $this->getValue('license');
    }
    

    /**
     * @return array
     */
    public function getAuthors()
    {
        return $this->getValue('authors');
    }
    
    /**
     * The absolute package installation root path
     * 
     * @return string
     */
    public function getAbsoluteRootPath()
    {
        return $this->getValue('root-path');
    }
}

```

**Comment by Ocramius** [comment]
I get what you want to do, I don't get:

 * why this fits this package
 * why is performance-sensitive a requirement
 * why can't the class do a lookup of the `composer.lock` instead of involving build-time codegen (which fails, a lot...)

Also, many of the structures involved are already defined in `composer/composer`, which may as well become a dependency, should package operations be required at runtime.

**Comment by ThaDafinser** [comment]
Currently i need to know those 3 things
- know if a package is installed
- know the installed version of a package
- know the installed tag/branch datetime of a package

Those 3 things i detect and read currently ugly/slow - with composer.json and composer.lock involved
https://github.com/ThaDafinser/UserAgentParser/blob/f087a38db03cc746039666087ee00d1aa126b8b7/src/Provider/WhichBrowser.php#L85-L87
https://github.com/ThaDafinser/UserAgentParser/blob/f087a38db03cc746039666087ee00d1aa126b8b7/src/Provider/AbstractProvider.php#L130-L194

> why is performance-sensitive a requirement

Since i check the package installation everytime and display the version + date for 18 packages, there are a lot of calls - that's why a solution with a better performance would be really great.
Example - http://useragent.mkf.solutions/

> why this fits this package

That was also my initial question. If you dont think it fits in here, i will create a new package/plugin with it.
Since my work is based also on your work here, i wanted to share it first with you.

**Comment by Ocramius** [comment]
> know if a package is installed

kinda weird, but I agree that we can add a getter for `isInstalled` or such: not much work to be done.

 > know the installed tag/branch datetime of a package

This seems weird

 > Since i check the package installation everytime and display the version + date for 18 packages, there are a lot of calls - that's why a solution with a better performance would be great.

I agree, but you still need to think about the 80/20 scenario. The 80% scenario here is "generate some sort of hash/prefix for assets depending on dependency versions/deployed version".

I'd say that you should first extract to your own package, and then we integrate it in here if I get more requests for this sort of feature.

**Comment by ThaDafinser** [comment]
@Ocramius i published now this package https://github.com/ThaDafinser/PackageInfo

If i "copied" to much ideas/code from you, feel free to ping me!

Seem to work well https://github.com/ThaDafinser/UserAgentParser/pull/99/files

**Comment by Ocramius** [comment]
@ThaDafinser this project is MIT: if you think that anything was copied, all you have to do is just mention the source somewhere in a comment.
