### ISSUE TITLE
Short version

### ISSUE THREAD

**Issue by theofidry** [Ocramius/PackageVersions#44]
Looking at https://github.com/Ocramius/example-symfony-cli-usage/pull/4, the version displayed will be something like `3.0.0@f9844cfd7179b1e279c0a78e41d96cb710858763`. Although I understand the motivation behind displaying the commit reference as well, I don't actually think a lot of people would like that, hence maybe providing a `Versions::getShortVersion()` displaying `3.0.0` would be a nice to have.

**Comment by Ocramius** [comment]
Reasons for this to be closed are explained in https://github.com/Ocramius/PackageVersions/issues/43
