### ISSUE TITLE
Error Installer.php on line 104

### ISSUE THREAD

**Issue by romainlaisne** [Ocramius/PackageVersions#45]
I am getting this error while updating with Composer:

Loading composer repositories with package information                                                                                     Updating dependencies (including require-dev)           - Installing ocramius/package-versions (1.1.2)
    Downloading: 100%         

Parse error: syntax error, unexpected ':', expecting ';' or '{' in 
[....]l/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 104

**Comment by romainlaisne** [comment]
![image](https://user-images.githubusercontent.com/7721517/27031864-544d707a-4f72-11e7-9f13-3acd99164fe7.png)

**Comment by romainlaisne** [comment]
Apparently due to PHP version.

**Comment by Ocramius** [comment]
This package requires PHP 7.1

**Comment by theofidry** [comment]
@Ocramius you only putted PHP 7.0 in the `composer.json` though.

@romainlaisne this looks a bit weird, if you're not in PHP7 you should have had an error as there's there's a PHP 7.0+ requirement in the `composer.json` of this package

**Comment by Ocramius** [comment]
Ah yeah, I should bump the requirements

**Comment by Ocramius** [comment]
Ah yeah, I should bump the requirements
