### ISSUE TITLE
Root package version show normalized in a version-branch

### ISSUE THREAD

**Issue by Jean85** [Ocramius/PackageVersions#52]
This was originally reported in https://github.com/Jean85/pretty-package-versions/issues/4; basically #51 doesn't work when the root package is in a version-branch (i.e. `3.0`).

This will be fixed when https://github.com/composer/composer/issues/6845 will be fixed.

This is a release blocker (as said by @Ocramius in https://github.com/composer/composer/issues/6845#issuecomment-347123240).

**Comment by Jean85** [comment]
https://github.com/composer/composer/pull/6845 has been fixed, this should be resolved with the next Composer's patch.

**Comment by Ocramius** [comment]
:+1:

**Comment by Ocramius** [comment]
https://github.com/composer/composer/releases/tag/1.5.3 released, so this can be shipped!

Ref: https://github.com/composer/composer/commit/5ba6d7d4364b0d1898017436935b863d4d8fb14d
