### ISSUE TITLE
Add a method to get all packages

### ISSUE THREAD

**Issue by aschempp** [Ocramius/PackageVersions#53]
It would be helpful to have a method to get all packages (instead of directly accessing the constant). I can provide a pull request, just wanted to check first if that would be a useful feature to you?

**Comment by Ocramius** [comment]
@aschempp accessing the constant is preferrable here

**Comment by aschempp** [comment]
Accessing the constant won't help with the `FallbackVersions` though, as it could provide the list of packages from the `composer.lock` in that case 😉

**Comment by Ocramius** [comment]
Yeah, I don't think I'd want to go down that route, and would probably rather deprecate the fallback approach and cause a hard failure at install instead...

**Comment by aschempp** [comment]
okay, I can live with that :-)
