### ISSUE TITLE
Consider adding Versions::getRootPackageVersion()

### ISSUE THREAD

**Issue by rybakit** [Ocramius/PackageVersions#55]
Having `Versions::getRootPackageVersion()` will allow to replace "hard-coded" root package names (like [here](https://github.com/amphp/aerys/blob/e4198fbcfc5791525c8913f75ef20915a402cc2e/lib/constants.php#L6) and [here](https://github.com/Ocramius/example-symfony-cli-usage/blob/a84b56e52b2719646fddda6b4b4bfa4918b33783/container.php#L20)),  which can be usefull for skeleton repositories.

Atm, I use  `$rootPackageVersion = array_values(array_slice(Versions::VERSIONS, -1))[0];`, but this seems more like a hack than a proper solution.

**Comment by Ocramius** [comment]
More than that, I'd rather expose the root package name and leave the API surface as small as possible. Thoughts?

Effectively, this means adding a class name to the generated code.

**Comment by Jean85** [comment]
I would be interested in having/doing this too!

**Comment by rybakit** [comment]
@Ocramius Sorry, I didn't quite understand how you propose to expose the root package name. Do you mean adding a constant to the generated class, eg

```
$version = Versions::getVersion(Versions::ROOT_PACKAGE_NAME);
```
?

**Comment by Ocramius** [comment]
Correct - that should be a sufficient first implementation

**Comment by rybakit** [comment]
https://github.com/Ocramius/PackageVersions/pull/56
