### ISSUE TITLE
The type error of the function's response

### ISSUE THREAD

**Issue by alekstar79** [Ocramius/PackageVersions#71]
The following signatures are present in the function code:
`PackageVersions\Installer::activate(Composer $composer, IOInterface $io): void`
And the interface that the Installer implements has the following:
`Composer\Plugin\PluginInterface::activate(Composer $composer, IOInterface $io);`

The function returns nothing, it has an empty body at all. Because of this, the following error is emitted:

```
PHP Fatal error:  Uncaught TypeError: Return value of PackageVersions\Installer::activate() must be an instance of PackageVersions\void, none returned in /var/www/alekstars79/data/www/vendor/ocramius/package-versions/src/PackageVersions/Installer.php:62
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): PackageVersions\Installer->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(PackageVersions\Installer))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(384): Composer\Plugin\PluginManager->load in /var/www/alekstars79/data/www/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 62
```
If remove the return type, no error occurs.

**Comment by Ocramius** [comment]
Please upgrade to PHP 7.1+, as required by this packages's specified dependencies: https://github.com/Ocramius/PackageVersions/blob/1.3.0/composer.json#L13

**Comment by alekstar79** [comment]
> Please upgrade to PHP 7.1+, as required by this packages's specified dependencies: https://github.com/Ocramius/PackageVersions/blob/1.3.0/composer.json#L13

I understand that. Just missed that I have php7.0 installed on the server. I'm sorry for my inattention.

**Comment by Ocramius** [comment]
@alekstar79 please also read https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Make sure you always develop on an environment that is compatible if not same as production.
