### ISSUE TITLE
Parse error: parse error, expecting `';'' or `'{'' in vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 59

### ISSUE THREAD

**Issue by Aaarrrgggh** [Ocramius/PackageVersions#72]
Hi All,

I have installed Symfony 4 with composer. Everything is okay in the browser, but I can't update dependencies with composer. 

I have this error: 

Parse error: parse error, expecting `';'' or `'{'' in /Applications/MAMP/htdocs/app/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 59

I'm using MAMP 5, with PHP version 7.2.8

How can I fix this?

Thanks all

Alexander

**Comment by Ocramius** [comment]
Your web server is running a different version of PHP than the one in CLI.
