### ISSUE TITLE
Replaces are not recognized for packages

### ISSUE THREAD

**Issue by dmolineus** [Ocramius/PackageVersions#74]
At the moment the composer replace configuration is only handled for the root package. But it's also possible that regular packages defines replacements. It would be great if they are also recognized.

**Comment by Ocramius** [comment]
@dmolineus a `replace` is a SAT mechanism for replacing a package, but the replaced package is, in fact, not installed.

The actual name of the installed package is not the one that is being replaced, so the current behavior is expected/correct. If the `"replace"` directive was used to fetch the replacing package name and use its version instead, then `PackageVersion` would be exposing invalid information about what is actually installed.

Closing as `invalid`.
