### ISSUE TITLE
Offensive error message

### ISSUE THREAD

**Issue by cannibal** [Ocramius/PackageVersions#76]
I have used libs in this namespace for many years on very high quality PHP projects.

However, had the misfortune of encountering an unprofessional fallback message in FallbackVersions.

Grep for this:
       . 'then you are on your own, and we can\'t really help you. Fix your shit and cut the tooling some slack.',

More concerning I see tests have been written for it.

Dont mean to be holier than thou - and a jokes a joke - but think the maintainer should sort this out as its a little unprofessional.

**Comment by Ocramius** [comment]
Duplicate of https://github.com/Ocramius/PackageVersions/pull/73

This package is indeed provided as-is as per its license: I do provide professional services for consulting fees, should the feature of custom installation paths be required, but that's not the case in general. As in referenced discussions in the #73, I have no intention to change the wording.
