### ISSUE TITLE
return a object instead of a string

### ISSUE THREAD

**Issue by staabm** [Ocramius/PackageVersions#77]
in our use-case it would be more helpfull to have a value object returned from the api on which values (name, version, reference) could be obtained separately instead of a string.

would this be something we can agree on?

**Comment by Ocramius** [comment]
I'd rather keep this package extremely minimal: defining what a version looks like is not trivial (from what I saw in maintaining `roave/security-advisories`), so I'd rather defer this to @nikolaposa's work instead, and not have my own opinionated value types.

**Comment by staabm** [comment]
> so I'd rather defer this to @nikolaposa's work instead, and not have my own opinionated value types.

does this mean there is another package with a more complex api?

**Comment by Ocramius** [comment]
Correct: this package only focuses on providing the raw information.

**Comment by nikolaposa** [comment]
> > so I'd rather defer this to @nikolaposa's work instead, and not have my own opinionated value types.
> 
> does this mean there is another package with a more complex api (I am not aware of )?

@staabm This one for example: https://github.com/nikolaposa/version
