### ISSUE TITLE
No version set (parsed as 1.0.0) in detached HEAD

### ISSUE THREAD

**Issue by glensc** [Ocramius/PackageVersions#84]
The detached HEAD usually appears when doing `git rebase`.

I resolved conflicts in `composer.lock` and run `composer update --lock` while rebasing. This resulted `'No version set (parsed as 1.0.0)@'`, written to `Versions` class.

# Reproducer:

1. `git rebase -i HEAD~1` # choose `pick` -> `edit`
2. `composer.phar show -s | head -n10 | grep versions`
3. `composer update --lock`
4. `grep parsed vendor/ocramius/package-versions/src/PackageVersions/Versions.php`

**Comment by glensc** [comment]
note: similar problem has arisen in the past, but no resolution: https://github.com/composer/composer/issues/5432#issuecomment-255669875

i.e, i think composer should make a deeper guess what is the current version in detached HEAD state.

**Comment by Ocramius** [comment]
Seems like a bug for upstream

**Comment by Ocramius** [comment]
I'm gonna close here: this package does indeed not concern itself with `git rev-parse HEAD` semantics, so there's nothing that can be fixed on this end, sorry.

**Comment by glensc** [comment]
the upstream (composer) does not want to solve this. I think I've linked relevant discussions.

**Comment by Ocramius** [comment]
Can't solve here either: we don't check the type of repository at all
