### ISSUE TITLE
Long term support of 1.2.0

### ISSUE THREAD

**Issue by kimpepper** [Ocramius/PackageVersions#86]
We are considering using this library for Drupal core. See https://www.drupal.org/project/drupal/issues/3005229

However, Drupal 8.8.x requires a minimum of PHP 7.0. Would you consider long-term support of the 1.2.0 release branch?

**Comment by Ocramius** [comment]
I'd only consider security fixes though

**Comment by kimpepper** [comment]
That should be sufficient, I think? FYI Drupal 8 is EOL November 2021, so we need support until then.

**Comment by staabm** [comment]
we would also love a 1.2.0 supported version, since we built on ubuntu lts and have to live with 7.0 until those boxes get updated to ubuntu20 in 2020

**Comment by Ocramius** [comment]
Closing here: as mentioned in https://github.com/Ocramius/PackageVersions/issues/86#issuecomment-489474942, feel free to contact me for any security issues that may arise in older releases :+1:

**Comment by staabm** [comment]
In case someone else is interessted - we will maintain a fork for this lib with php7.0 compat: https://packagist.org/packages/complex/package-versions
