### ISSUE TITLE
classes are generated twice on "composer update"

### ISSUE THREAD

**Issue by staabm** [Ocramius/PackageVersions#94]
https://github.com/Ocramius/PackageVersions/pull/91 made sure we can now run `composer dump-autoload` to regenerate the package-versions.

it seems as a side effect this now leads to `composer update` (and I guess also `composer install`) generates the classes twice.

```
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
complex/package-versions: Generating version class...
complex/package-versions: ...done generating version class
complex/package-versions: Generating version class...
complex/package-versions: ...done generating version class
```

I dont have time to analyze it deeper right now, but wanted to leave it here in case someone else has a few minutes to fix it

**Comment by Ocramius** [comment]
Hmm, wondering if that is a bigger issue, or if it can simply be skipped...

Also: maybe we should skip class generation overall during `install` or `update`, and only keep it when the autoloader is dumped?
